In [2]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
training_set = tf.keras.utils.image_dataset_from_directory(
    "dataset/train",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 70295 files belonging to 38 classes.


In [4]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    "dataset/valid",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [5]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [6]:
for x,y in training_set:
    print(x, x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[111.5   98.5  105.5 ]
   [104.5   91.5   98.5 ]
   [110.25  97.25 104.25]
   ...
   [111.    99.   109.  ]
   [111.5   99.5  109.5 ]
   [107.25  95.25 105.25]]

  [[113.   100.   107.  ]
   [111.    98.   105.  ]
   [104.75  91.75  98.75]
   ...
   [113.   101.   111.  ]
   [111.5   99.5  109.5 ]
   [112.   100.   110.  ]]

  [[111.25  98.25 105.25]
   [116.   103.   110.  ]
   [108.25  95.25 102.25]
   ...
   [116.25 104.25 114.25]
   [113.25 101.25 111.25]
   [114.25 102.25 112.25]]

  ...

  [[157.75 148.75 153.75]
   [159.25 150.25 155.25]
   [166.25 157.25 162.25]
   ...
   [167.75 161.75 171.75]
   [165.   159.   169.  ]
   [162.25 156.25 166.25]]

  [[160.5  151.5  156.5 ]
   [159.25 150.25 155.25]
   [164.5  155.5  160.5 ]
   ...
   [170.25 164.25 174.25]
   [167.25 161.25 171.25]
   [166.75 160.75 170.75]]

  [[163.75 154.75 159.75]
   [162.25 153.25 158.25]
   [157.   148.   153.  ]
   ...
   [162.   156.   166.  ]
   [157.25 151.25 161.25]
   [160.   154.   16

In [7]:
from tensorflow.keras.layers import Dense, Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

In [8]:
model = Sequential()

In [9]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

c:\Users\Admin\Documents\OneDrive\Desktop\crop-disease-detection\venv311\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [11]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [12]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [13]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [14]:
model.add(Dropout(0.25))

In [15]:
model.add(Flatten())

In [16]:
model.add(Dense(units=1500,activation='relu'))

In [17]:
model.add(Dropout(0.4))

In [18]:
model.add(Dense(units=38,activation='softmax'))

In [19]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        57,038 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

In [21]:
training_history= model.fit(x=training_set,validation_data=validation_set,epochs=8)

Epoch 1/8


2197/2197 ━━━━━━━━━━━━━━━━━━━━ 5728s 3s/step - accuracy: 0.3766 - loss: 2.2305 - val_accuracy: 0.8441 - val_loss: 0.4914
Epoch 2/8
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 5370s 2s/step - accuracy: 0.8309 - loss: 0.5414 - val_accuracy: 0.9054 - val_loss: 0.2951
Epoch 3/8
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 5196s 2s/step - accuracy: 0.9014 - loss: 0.3085 - val_accuracy: 0.9236 - val_loss: 0.2361
Epoch 4/8
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 5266s 2s/step - accuracy: 0.9333 - loss: 0.2057 - val_accuracy: 0.9262 - val_loss: 0.2384
Epoch 5/8
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 5974s 3s/step - accuracy: 0.9517 - loss: 0.1465 - val_accuracy: 0.9528 - val_loss: 0.1533
Epoch 6/8
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 6263s 3s/step - accuracy: 0.9624 - loss: 0.1140 - val_accuracy: 0.9503 - val_loss: 0.1550
Epoch 7/8
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 6374s 3s/step - accuracy: 0.9690 - loss: 0.0946 - val_accuracy: 0.9472 - val_loss: 0.1861
Epoch 8/8
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 6315s 3s/step - accuracy: 0.9736 - loss: 0.0804 - va

In [22]:
train_loss,train_acc = model.evaluate(training_set)

2197/2197 ━━━━━━━━━━━━━━━━━━━━ 38778s 18s/step - accuracy: 0.9799 - loss: 0.0587


In [23]:
print(train_loss,train_acc)

0.054194070398807526 0.9811508655548096


In [24]:
val_loss,val_acc = model.evaluate(validation_set)

550/550 ━━━━━━━━━━━━━━━━━━━━ 330s 597ms/step - accuracy: 0.9522 - loss: 0.1550


In [25]:
print(val_loss,val_acc)

0.15610483288764954 0.9521397948265076


In [26]:
model.save("trained_model1.keras")

In [27]:
model.save("trained_model1.h5") 

In [28]:
training_history.history

{'accuracy': [0.5855608582496643,
  0.8555231690406799,
  0.9110320806503296,
  0.9385305047035217,
  0.9551888704299927,
  0.9645636081695557,
  0.9706095457077026,
  0.9757166504859924],
 'loss': [1.4143916368484497,
  0.4577128291130066,
  0.27511879801750183,
  0.18833445012569427,
  0.13574883341789246,
  0.10618936270475388,
  0.08826163411140442,
  0.0745173767209053],
 'val_accuracy': [0.8440701365470886,
  0.9053608179092407,
  0.9235715866088867,
  0.9261893630027771,
  0.9528226852416992,
  0.9503186941146851,
  0.9471887350082397,
  0.9521397948265076],
 'val_loss': [0.4913681149482727,
  0.2950626313686371,
  0.23612616956233978,
  0.2383503019809723,
  0.15330061316490173,
  0.15495885908603668,
  0.18614070117473602,
  0.15610487759113312]}

In [29]:
import json
with open("training_hist.json","w") as f:
    json.dump(training_history,f)

TypeError: Object of type History is not JSON serializable

In [ ]:
training_history.history['val_accuracy']

In [ ]:
epochs = [i for i in range (1,11)]
plt.plot(epochs,training_history.history['accuracy'],color='red',label='Training Accuracy')
plt.plot(epochs,training_history.history['val_accuracy'],color='blue',label='Validation Accuracy')
plt.xlabel("No of Epochs")
plt.ylabel("Accuracy Result")
plt.title("visulization of accuracy result")
plt.legend()
plt.show()

In [ ]:
class_name = validation_set.class_names
class_name

In [ ]:
test_set = tf.keras.utils.      image_dataset_from_directory(
    "valid",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

In [ ]:
y_pred = model.predict(test_set)
y_pred,y_pred.shape

In [ ]:
predicted_categories = tf.argmax(y_pred,axis=1)

In [ ]:
predicted_categories

In [ ]:
true_categories = tf.concat([y for x,y in test_set],axis=0)
true_categories

In [ ]:
Y_true = tf.argmax(true_categories,axis=1)
Y_true

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(classification_report(Y_true,predicted_categories,target_names=class_name))

In [ ]:
cm = confusion_matrix(Y_true,predicted_categories)
cm

In [ ]:
plt.figure(figsize=(40,40))
sns.heatmap(cm,annot=True,annot_kws={'size':10})
plt.xlabel("Predicted Class",fontsize=20)
plt.ylabel("Actual Class",fontsize=20)
plt.title("Plant Disease Prediction Confusion Matrix",fontsize=25)
plt.show()